### ISSUE TITLE
[Feature]: Ability to modify config values per runtime (for testing purposes)

### ISSUE THREAD

**Issue by hypeofpipe** [Matii96/unifig#15]
### Is there an existing issue for this?

- [X] I've not found one

### What is a reason behind changing the behavior?

The current implementation of the Config Manager in Nest.js is global per runtime, which means that all modules share the same configuration object. This can lead to unexpected side effects and issues when writing tests, as changes made to the configuration during a test run might affect other tests or test suites.

The primary motivation for this change is to improve the testability of the application by allowing developers to create isolated configuration instances for individual test suites. This ensures that configuration changes made during a test run do not affect other test suites, leading to more reliable and easier-to-maintain tests.

E.g., if we have to test a module that has different behaviours based on envs, we will write such test cases:

- root module
- root module > when env "boo" is false
- root module > when env "boo" is true

And the Config would be shared for each test suite.

### Propose the solution

A clear and concise description of the solution with considered benefits and drawbacks

A possible solution is to provide a utility function that generates a new instance of ConfigManager for each test suite, allowing developers to have isolated configurations for different test suites.

Benefits:

- Improved testability of the application
- Isolated configuration instances for different test suites
- Easier-to-maintain and more reliable tests

Drawbacks:

- Additional utility function to be maintained
- Slightly increased complexity in test setup

### Adoption

The proposed solution should not (I'm not sure 😅) introduce breaking changes to the existing implementation. Developers can continue using the global configuration object in their applications, while using the new utility function to create isolated configurations for test suites. No migration is necessary for existing applications.

**Comment by Matii96** [comment]
`Config` object is an global instance of `ConfigManager`. Such can be created via
```ts
import { ConfigManagerFactory } from '@unifig/core';

const config = ConfigManagerFactory.create();

const validationError = config.registerSync({
  templates: [AppOptions],
  adapter: new EnvConfigAdapter(),
});

const options = config.getValues(AppOptions);
```
instead of 
```ts
import { Config } from '@unifig/core';

const validationError = Config.registerSync({
  templates: [AppOptions],
  adapter: new EnvConfigAdapter(),
});

const options = Config.getValues(AppOptions);
```
